#! /bin/bash

./gradlew clean
./gradlew dist
rm -rf server
mkdir server
cp /home/lachlan/Starmyth/starmyth-client/desktop/build/libs/desktop-1.0.jar server/server.jar
cp -rf /home/lachlan/Starmyth/starmyth-client/core/assets/* /home/lachlan/Starmyth/starmyth-client/server/
